import test from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { defaultConfig, configSchema, calculateDay, dateAt, formatTime, TIMES, nextPrayer,
  toHijri, fromHijri, islamicDays, calendarRows, calendarCsv, calendarIcs, parseDate, addDays,
  eventsForDay, eventsAround, AudioQueue } from '../dist/index.js';

function configAt(latitude, longitude, timeZone) {
  const c = defaultConfig(); Object.assign(c.locations[0], { latitude, longitude, timeZone }); return c;
}

// Numeric fixture independently recorded in the upstream test suite, not generated by this wrapper.
// https://github.com/batoulapps/adhan-js/blob/develop/test/adhan.test.ts (calculating prayer times)
test('published Raleigh reference fixture, all six times', () => {
  const c = configAt(35.775, -78.6336, 'America/New_York');
  c.calculation.method = 'NorthAmerica'; c.calculation.madhab = 'Hanafi'; c.calculation.maghribAfterSunset = 0;
  const day = calculateDay(c, '2015-07-12');
  assert.deepEqual(TIMES.map(p => formatTime(day.times[p], day.timeZone, false)), ['04:42', '06:08', '13:21', '18:22', '20:32', '21:57']);
});
test('published Sydney Qibla reference', () => {
  const day = calculateDay(configAt(-33.8688, 151.2093, 'Australia/Sydney'), '2026-09-13');
  assert.ok(Math.abs(day.qibla - 277.4996) < 0.001);
});
test('Hanafi changes Asr without moving the other prayers', () => {
  const c = defaultConfig(), a = calculateDay(c, '2026-09-13');
  c.calculation.madhab = 'Hanafi'; const b = calculateDay(c, '2026-09-13');
  assert.ok(+b.times.asr - +a.times.asr > 30 * 60000);
  for (const p of TIMES.filter(p => p !== 'asr')) assert.equal(+a.times[p], +b.times[p]);
});
test('all minute adjustments apply once, with no accumulated mutation', () => {
  const c = defaultConfig(), before = calculateDay(c, '2026-09-13');
  c.calculation.adjustments.fajr = -3; c.calculation.adjustments.maghrib = 5;
  const after = calculateDay(c, '2026-09-13');
  assert.equal(+after.times.fajr - +before.times.fajr, -180000);
  assert.equal(+after.times.maghrib - +before.times.maghrib, 300000);
  assert.deepEqual(calculateDay(c, '2026-09-13'), after);
});
test('Melbourne DST spring transition changes local display without a UTC hour jump', () => {
  const c = defaultConfig(), a = calculateDay(c, '2026-10-03'), b = calculateDay(c, '2026-10-04');
  const minute = d => { const [h, m] = formatTime(d, a.timeZone, false).split(':').map(Number); return h * 60 + m; };
  assert.ok(minute(b.times.dhuhr) - minute(a.times.dhuhr) >= 58);
  assert.ok(Math.abs((+b.times.dhuhr - +a.times.dhuhr) / 60000 - 1440) <= 2);
});
test('Melbourne autumn DST transition shifts local display back', () => {
  const c = defaultConfig(), a = calculateDay(c, '2026-04-04'), b = calculateDay(c, '2026-04-05');
  const minute = d => { const [h, m] = formatTime(d, a.timeZone, false).split(':').map(Number); return h * 60 + m; };
  assert.ok(minute(b.times.dhuhr) - minute(a.times.dhuhr) <= -58);
});
test('UTC output is independent of the host time zone', () => {
  const script = "import {defaultConfig,calculateDay} from './dist/index.js'; console.log(JSON.stringify(calculateDay(defaultConfig(),'2026-10-04')));";
  const results = ['UTC', 'America/Los_Angeles', 'Asia/Tokyo'].map(TZ => {
    const child = spawnSync(process.execPath, ['--input-type=module', '-e', script], { encoding: 'utf8', env: { ...process.env, TZ } });
    assert.equal(child.status, 0, child.stderr); return child.stdout;
  });
  assert.equal(results[0], results[1]); assert.equal(results[1], results[2]);
});
test('civil date line: Kiritimati prayers belong to the requested local date', () => {
  const c = configAt(1.8721, -157.4278, 'Pacific/Kiritimati');
  const d = calculateDay(c, '2026-09-13');
  for (const prayer of TIMES) assert.equal(dateAt(d.times[prayer], d.timeZone), d.date);
});
test('Umm al-Qura adds 30 minutes during Ramadan and does not mutate config', () => {
  const c = configAt(21.4225, 39.8262, 'Asia/Riyadh'); c.calculation.method = 'UmmAlQura';
  const date = fromHijri(1447, 9, 10), normal = fromHijri(1447, 8, 10);
  const ramadan = calculateDay(c, date), other = calculateDay(c, normal);
  assert.equal((+ramadan.times.isha - +ramadan.sunset) / 60000, 120);
  assert.equal((+other.times.isha - +other.sunset) / 60000, 90);
});
test('custom Isha angle overrides the preset fixed interval', () => {
  const c = defaultConfig(); c.calculation.method = 'UmmAlQura'; c.calculation.ishaAngle = 17;
  const a = calculateDay(c, '2026-09-13'); c.calculation.ishaInterval = 90;
  const b = calculateDay(c, '2026-09-13'); assert.notEqual(+a.times.isha, +b.times.isha);
});
test('unresolved polar prayers are explicit nulls, and never scheduled', () => {
  const c = configAt(69.6492, 18.9553, 'Europe/Oslo'), d = calculateDay(c, '2026-06-21');
  assert.equal(d.times.sunrise, null); assert.ok(d.warnings.length);
  assert.ok(eventsForDay(c, d.date).every(e => Number.isFinite(+e.at)));
});
test('polar nearest-location fallback produces estimates', () => {
  const c = configAt(69.6492, 18.9553, 'Europe/Oslo'); c.calculation.polarResolution = 'AqrabBalad';
  const d = calculateDay(c, '2026-06-21'); assert.ok(d.times.sunrise); assert.match(d.warnings.join(), /fallback/);
});
test('next prayer after Isha is tomorrow Fajr; sunrise is never an Athan', () => {
  const c = defaultConfig(), d = calculateDay(c, '2026-09-13');
  const n = nextPrayer(c, new Date(+d.times.isha + 1000)); assert.equal(n.prayer, 'fajr'); assert.equal(n.date, '2026-09-14');
  assert.equal(nextPrayer(c, new Date(+d.times.fajr + 1000)).prayer, 'dhuhr');
});
test('last third uses tomorrow Fajr, including the date rollover', () => {
  const c = defaultConfig(), a = calculateDay(c, '2026-09-13'), b = calculateDay(c, '2026-09-14');
  assert.ok(Math.abs(+a.lastThirdOfNight - (+a.times.maghrib + (+b.times.fajr - +a.times.maghrib) * 2 / 3)) < 1);
  assert.equal(dateAt(a.lastThirdOfNight, a.timeZone), '2026-09-14');
});
test('Hijri round trips Gregorian leap day, year boundaries and corrections', () => {
  for (const date of ['2024-02-29', '2025-12-31', '2026-01-01', '2026-09-13']) for (const adjustment of [-2, 0, 2]) {
    const h = toHijri(date, adjustment); assert.equal(fromHijri(h.year, h.month, h.day, adjustment), date);
  }
  const h = toHijri('2026-09-13'); assert.deepEqual([h.year, h.month, h.day], [1448, 4, 2]);
});
test('invalid Gregorian and Hijri dates fail explicitly', () => {
  for (const date of ['2026-02-29', '2026-13-01', '2026-1-01', 'invalid']) assert.throws(() => parseDate(date));
  assert.throws(() => fromHijri(1448, 13, 1)); assert.throws(() => toHijri('2026-09-13', 3));
});
test('Islamic event estimates round-trip to their Hijri dates', () => {
  for (const event of islamicDays(1448)) {
    const h = toHijri(event.date); assert.equal(h.month, event.month); assert.equal(h.day, event.day); assert.equal(event.estimated, true);
  }
});
test('calendar export covers leap month and leap year', () => {
  const c = defaultConfig(); assert.equal(calendarRows(c, '2028-02-01', '2028-02-29').length, 29);
  assert.equal(calendarRows(c, '2028-01-01', '2028-12-31').length, 366);
  assert.equal(calendarCsv(c, '2026-09-13', '2026-09-13').trim().split('\r\n').length, 2);
});
test('ICS contains stable IDs, UTC times, five events a day and safe UTF-8 folding', () => {
  const c = defaultConfig(); c.locations[0].name = 'مدينة'.repeat(40) + ',;\nEND:VEVENT';
  const text = calendarIcs(c, '2026-09-13', '2026-09-14', new Date('2026-01-01T00:00:00Z'));
  assert.equal((text.match(/BEGIN:VEVENT/g) ?? []).length, 10);
  assert.equal((text.match(/DTSTART:\d{8}T\d{6}Z/g) ?? []).length, 10);
  assert.ok(text.split('\r\n').every(line => Buffer.byteLength(line) <= 75));
  assert.ok(!text.includes('\r\nEND:VEVENT\r\nEND:VEVENT'));
  assert.equal(text, calendarIcs(c, '2026-09-13', '2026-09-14', new Date('2026-01-01T00:00:00Z')));
});
test('configuration rejects unknown keys, duplicate IDs and invalid calculation inputs', () => {
  for (const mutate of [c => c.typo = true, c => c.locations[0].timeZone = 'Nowhere/Invalid', c => c.locations[0].latitude = NaN,
    c => c.locations.push(c.locations[0]), c => c.activeLocation = 'missing', c => c.calculation.method = 'Other',
    c => c.audio.volume = 101, c => c.scheduler.days = [7]]) {
    const c = defaultConfig(); mutate(c); assert.throws(() => configSchema.parse(c));
  }
});
test('night-crossing reminders remain attached to the prayer date and weekday', () => {
  const c = configAt(60.1699, 24.9384, 'Europe/Helsinki');
  c.reminders = [{ id: 'before-fajr', prayer: 'fajr', offsetMinutes: -180, file: null, repeat: 1, enabled: true }];
  const events = eventsForDay(c, '2026-06-21');
  const reminder = events.find(e => e.kind === 'reminder');
  assert.equal(dateAt(reminder.at, c.locations[0].timeZone), '2026-06-20');
  assert.ok(eventsAround(c, reminder.at).some(e => e.id === reminder.id));
  c.scheduler.days = [6]; assert.equal(eventsForDay(c, '2026-06-21').length, 0);
});
test('audio sequences are serialized and a new prayer interrupts an active reminder', async () => {
  const calls = []; let started;
  const beginning = new Promise(r => started = r);
  const player = (file, options) => {
    calls.push(file);
    if (file === 'reminder') return new Promise((resolve, reject) => { options.signal.addEventListener('abort', () => reject(new Error('interrupted'))); started(); });
    return Promise.resolve('ok');
  };
  const queue = new AudioQueue(player), settings = { volume: 0, maxSeconds: 1 };
  const reminder = queue.enqueue(['reminder'], 1, 'reminder', settings);
  const rejected = assert.rejects(reminder, /interrupted/);
  await beginning; await queue.enqueue(['athan', 'dua'], 1, 'athan', settings); await rejected;
  assert.deepEqual(calls, ['reminder', 'athan', 'dua']); await queue.stop();
});
test('expired queued audio does not play', async () => {
  let called = false; const queue = new AudioQueue(async () => { called = true; return ''; }, () => 1000);
  await assert.rejects(queue.enqueue(['file'], 1, 'athan', { volume: 0, maxSeconds: 1 }, 999), /expired/);
  assert.equal(called, false); await queue.stop();
});
test('a new Athan moves ahead of reminders already waiting in the audio queue', async () => {
  const calls = []; let started;
  const beginning = new Promise(r => started = r);
  const player = (file, options) => {
    calls.push(file);
    if (file === 'active') return new Promise((resolve, reject) => { options.signal.addEventListener('abort', () => reject(new Error('interrupted'))); started(); });
    return Promise.resolve('ok');
  };
  const queue = new AudioQueue(player), settings = { volume: 0, maxSeconds: 1 };
  const active = assert.rejects(queue.enqueue(['active'], 1, 'reminder', settings), /interrupted/);
  await beginning;
  const waiting = queue.enqueue(['waiting-reminder'], 1, 'reminder', settings);
  const prayer = queue.enqueue(['athan', 'dua'], 1, 'athan', settings);
  await Promise.all([active, waiting, prayer]);
  assert.deepEqual(calls, ['active', 'athan', 'dua', 'waiting-reminder']); await queue.stop();
});
