import json
from pathlib import Path
path = Path('ui/src/i18n/catalogue.txt')
entries = {}
for line in path.read_text(encoding='utf-8').splitlines():
    if not line.strip(): continue
    parts = line.split('|')
    assert len(parts) == 6 and all(parts), line
    assert parts[0] not in entries, parts[0]
    entries[parts[0]] = parts[1:]
path.with_suffix('.json').write_text(json.dumps(entries,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
Path('src/translations.ts').write_text('// Generated by scripts/build-translations.py. Order: ar, ur, tr, id, fr.\nexport const translations: Record<string, readonly string[]> = '+json.dumps(entries,ensure_ascii=False,indent=2)+';\n',encoding='utf-8')
print(f'{len(entries)} interface phrases in five translated languages plus English')
